name: atari_frostbite
channels:
- pytorch
dependencies:
- python=3.7.9
- pytorch=1.7.1
- cudatoolkit=10.
- numpy=1.19.2
- psutil
- opencv
- pip=21.1.3
- pip:
  - git+git://github.com/mila-iqia/atari-representation-learning.git
  - atari-py==0.2.6
  - pyprind
  - tensorflow-gpu>=1.13
  - absl-py==0.13.0
  - gym==0.15.4
  - 'gym[atari]'
  - tqdm
  - transformers
  - blosc
  - imageio
  - wandb
